[build]
# Improve linking for PyO3 and Python integration
rustflags = [
    "-C", "link-arg=-Wl,--no-as-needed"
]

[env]
# Ensure consistent Python discovery
PYO3_PYTHON = { value = "python3", relative = false }

# Configuration for different target environments
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--no-as-needed"
]

[target.x86_64-apple-darwin] 
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup"
]

# Tarpaulin-specific configuration
[profile.test]
debug = true
opt-level = 0

# Additional configuration for tarpaulin compatibility
# Tarpaulin will use the standard target.x86_64-unknown-linux-gnu configuration
# Additional flags are handled in build.rs when tarpaulin is detected
