[package]
name = "persist-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core engine for agent snapshot and restore functionality"

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
flate2.workspace = true
thiserror.workspace = true
chrono.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3.0"
